version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./api:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
        - app
    depends_on:
      - api
  
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ipguardian
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8889:3306
    networks:
      - db
  
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www/api
    networks:
      - app
      - db
    working_dir: /var/www/api
    depends_on:
      - db
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client:/var/www/client
      - /var/www/client/node_modules
    networks:
      - app
    working_dir: /var/www/client
    depends_on:
      - api

networks:
    app:
        driver: bridge
    db:
